version: '3.1'

services:
  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - '27017:27017'
    volumes:
      - './volumenes/mongodb:/data/db'

  mongo-express:
      image: mongo-express
      restart: always
      depends_on:
        - mongo
      ports:
        - "8087:8081"
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: root
        ME_CONFIG_MONGODB_ADMINPASSWORD: example
        ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/

  db:
    container_name: server-mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: laura
    volumes:
      - './volumenes/postgres:/var/lib/mysql'
    hostname: server-mysql

  adminer:
    container_name: server-adminer
    image: adminer
    restart: always
    ports:
      - "8081:8080"
    hostname: server-adminer

  eureka:
    image: eureka-server
    restart: always
    ports:
      - "8761:8761"

  clientes:
    image: cliente-service
    restart: always
    depends_on:
      - mongo
      - eureka
    environment:
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
      - spring.data.mongodb.uri=mongodb://root:example@mongo:27017/clientes?authSource=admin

  libros:
    image: libro-service
    build: ./libros
    restart: always
    depends_on:
      - db
      - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/libros?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=laura
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka

  prestamos:
    image: prestamo-service
    restart: always
    depends_on:
    - db
    - eureka
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/prestamos?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=laura
      - eureka.client.service-url.defaultZone=http://eureka:8761/eureka

  gateway:
   image: gateway-service
   build: ./gateway
   restart: always
   depends_on:
     - eureka
     - clientes
     - libros
     - prestamos
   environment:
     - eureka.client.service-url.defaultZone=http://eureka:8761/eureka
   ports:
     - "8080:8080"