version: '3.1'

volumes:
  keycloak_data:

services:
  db:
    container_name: server-mysql
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - './volumenes/postgres:/var/lib/mysql'
    hostname: server-mysql


  adminer:
    container_name: server-adminer
    image: adminer
    restart: always
    ports:
      - 8081:8080
    hostname: server-adminer

  keycloak:
    image: quay.io/keycloak/keycloak:21.0.2
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    volumes:
      - 'keycloak_data:/opt/keycloak/data/'
    ports:
      - "9090:8080"

  eureka-server:
    build: ./eureka-server
    restart: always
    ports:
      - "8761:8761"

  pagos:
    image: pagos-service
    build: ./pagos
    restart: always
    environment:
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
      - spring.datasource.url=jdbc:mysql://mysql:3306/pagos?createDatabaseIfNotExist=true
      - spring.datasource.username=root
      - spring.datasource.password=root
  microservicios:
    build: ./microservicios
    restart: always
    depends_on:
      - keycloak
      - eureka-server
    environment:
      keycloack.admin-url: http://keycloak:8080/admin/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/tutorial-api
      URL_aut: http://keycloak:8080/realms/tutorial-api/protocol/openid-connect/token
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka

  gateway:
    build: ./gateway
    restart: always
    depends_on:
      - eureka-server
      - microservicios
      - keycloak
    environment:
      server.port: 8082
      spring.security.oauth2.resourceserver.jwt.issuer-uri: http://keycloak:8080/realms/tutorial-api
      spring.security.oauth2.resourceserver.jwt.jwk-set-uri: http://keycloak:8080/realms/tutorial-api/protocol/openid-connect/certs
      eureka.client.service-url.defaultZone: http://eureka-server:8761/eureka
    ports:
      - "8080:8082"
